### PR TITLE
Fix notice on CmsController.php 

### PR DESCRIPTION
**Pull request by MJ-Aristote**
Notice: Undefined variable: shop_sql in /override/controllers/front/CmsController.php on line 93

### CODE REVIEW

**Comment by ZiZuu-store** [comment]
Hi,
 thank you for your contribution.

I'm going to remove the Notice in a few hours.. I need to do a bit of refactoring on this piece of code, as the concatenation on an empty string  sounds bad 

Will inspect better ASAP

**Comment by ZiZuu-store** [comment]
Plz remove the .= operator on line 9 and substitute with simple = and I'll merge your patch


Thanks

**Comment by MJ-Aristote** [comment]
Done, but i don't agree.
Concatenation on empty string is allowed!
It's just on undefined string, it's not allowed.
Display an undefined string is not allowed too.

**Comment by ZiZuu-store** [comment]
I agree about the concatenation being allowed on empty string.. but what is the need for a concatenation ??

these lines are inizializing the var:
- empty
OR
- valorized

this code is intended to be equivalent to a ternary operator
```
$var = (IF) ? '' : value
```

**Comment by ZiZuu-store** [comment]
Can you redo the PR against **[dev](https://github.com/ZiZuu-store/zzCleanURLs/tree/dev) branch**?

Thanks

**Comment by ZiZuu-store** [comment]
Merged, tnx

**Pull request merged**
